server.port: 8080
spring:
  application:
    name: customer
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:customer}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:qweqwe123}
  liquibase:
    change-log: classpath:/db/changelog-master.xml
    contexts: local
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
      topic: topic
    event:
      group_id: ${spring.application.name}
  jpa:
    show-sql: false
    database: POSTGRESQL
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher