package com.lesha.saga.kafka.consumer

enum class ActionType {
    CUSTOMER_CREATED,

    CUSTOMER_BALANCE_RESERVED,
    CUSTOMER_BALANCE_RESERVE_FAILED,
    CUSTOMER_BALANCE_RESERVE_CANCEL,
    OFFER_CREATED,
    OFFER_CREATED_FAILED,
    OFFER_CANCELED,

    EXCHANGE_OFFER_CANCELED,
    EXCHANGE_OFFER_COMPLETED,
    EXCHANGE_OFFER_FAILED,
    EXCHANGE_OFFER_PENDING,
    EXCHANGE_OFFER_RESERVED,
}
