package com.lesha.saga.kafka.consumer

enum class ActionType {
    CUSTOMER_BALANCE_RESERVED,

    OFFER_CREATED,
    OFFER_CREATED_FAILED,
    OFFER_CANCELED,
    OFFER_CANCELLATION_PENDING,

    EXCHANGE_OFFER_CANCELED,
    EXCHANGE_OFFER_CANCELLATION_FAILED,
    EXCHANGE_OFFER_COMPLETED,
    EXCHANGE_OFFER_FAILED,
    EXCHANGE_OFFER_RESERVED,
    EXCHANGE_OFFER_RESERVATION_FAILED,
    OFFER_ROLLBACK,
}
