server.port: 8081
spring:
  application:
    name: offer
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:offer}
    username: ${DB_USERNAME:app_user}
    password: ${DB_PASSWORD:Qw123456}
  liquibase:
    change-log: classpath:/db/changelog-master.xml
    contexts: local
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
      topic: topic
    event:
      group_id: ${spring.application.name}
    retry:
      topic:
        attempts: 3
  jpa:
    show-sql: false
    database: POSTGRESQL
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher