package com.lesha.saga.kafka.consumer

enum class ActionType {
    CUSTOMER_BALANCE_RESERVED,
    CUSTOMER_BALANCE_RESERVE_CANCEL,
    ORDER_CREATED,
    ORDER_CANCELED,

    EXCHANGE_ORDER_CANCELED,
    EXCHANGE_ORDER_COMPLETED,
    EXCHANGE_ORDER_FAILED,
    EXCHANGE_ORDER_PENDING,
}
