package com.lesha.saga.kafka.consumer

enum class ActionType {
    CUSTOMER_CREATED,

    CUSTOMER_BALANCE_RESERVED,
    CUSTOMER_BALANCE_RESERVE_CANCEL,
    CUSTOMER_BALANCE_RESERVE_FAILED,
    OFFER_CREATED,
//    OFFER_CREATED_FAILED,
    OFFER_CANCELLATION_PENDING,
    OFFER_CANCELLATION_PENDING_FAILED,
    OFFER_CANCELED,
    OFFER_CANCELED_FAILED,
    OFFER_COMPLETED,
    OFFER_COMPLETED_FAILED,
    OFFER_ROLLBACK,

    EXCHANGE_OFFER_CANCELED,
    EXCHANGE_OFFER_COMPLETED,
    EXCHANGE_OFFER_COMPLETED_FAILED,
    EXCHANGE_OFFER_FAILED,
    EXCHANGE_OFFER_RESERVED,
    EXCHANGE_OFFER_RESERVATION_FAILED,
    OFFER_ROLLBACK_FAILED,
}
